# Generated by Django 5.2.8 on 2026-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('mens', 'Mens'), ('womens', 'Womens')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
