# Generated by Django 5.2.8 on 2026-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide_category_alter_heroslide_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional heading shown over video', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Optional description text')),
                ('video', models.FileField(help_text='Upload MP4 video (muted, short)', upload_to='home_videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Video',
                'verbose_name_plural': 'Homepage Video',
            },
        ),
    ]
