# Generated by Django 5.2.8 on 2026-01-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
