# Generated by Django 5.2.8 on 2026-02-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_variant_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Order',
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Order',
                'verbose_name_plural': 'Pending Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Processing Order',
                'verbose_name_plural': 'Processing Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ShippedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Shipped Order',
                'verbose_name_plural': 'Shipped Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
