# Generated by Django 5.2.8 on 2026-01-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Example: #000000', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='Example: Black, Olive Green, Wine Red', max_length=50),
        ),
    ]
