# Generated by Django 5.2.8 on 2026-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_color_hex_alter_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_description',
            field=models.TextField(blank=True, help_text='Story text shown below product details'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_title',
            field=models.CharField(default='Designed for everyday layering', max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='Example: Black, Olive Green, Wine Red', max_length=15),
        ),
    ]
