# Generated by Django 5.2.8 on 2026-01-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_style_description_product_style_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section heading (e.g. Designed for everyday layering)', max_length=255)),
                ('description', models.TextField(help_text='Section content')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_sections', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
