# Generated by Django 5.2.8 on 2026-01-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_options_product_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Size Guide', max_length=200)),
                ('content', models.TextField(help_text='Use line breaks or table-style text')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_guide', to='products.product')),
            ],
        ),
    ]
